# Generated by Django 3.0.6 on 2020-06-14 21:50

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('message', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('general', models.BooleanField(default=True)),
                ('receiver', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('sex', models.CharField(default=None, max_length=6, null=True)),
                ('phone', models.CharField(default=None, max_length=16, null=True)),
                ('user_data', models.TextField(blank=True, default=None, null=True)),
                ('choice_data', models.TextField(blank=True, default=None, null=True)),
                ('deal_breaker', models.CharField(blank=True, max_length=64)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_pics')),
                ('matches', models.CharField(blank=True, default='', max_length=10)),
                ('successful_matches', models.TextField(blank=True, default=None, null=True)),
                ('no_matches', models.TextField(blank=True, default=None, null=True)),
                ('jilted_matches', models.TextField(blank=True, default=None, null=True)),
                ('notification', models.TextField(blank=True, default=None, null=True)),
                ('profile_changed', models.BooleanField(default=False)),
                ('dating', models.BooleanField(default=False)),
                ('payed', models.BooleanField(default=False)),
                ('min_score', models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('first_partner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='match1', to=settings.AUTH_USER_MODEL)),
                ('second_partner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='match2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
