# Generated by Django 3.0.6 on 2020-07-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secret',
            field=models.BinaryField(default=b'YiE6jxijpB5EJsZ0VRjvNPpUXQCphzfeKfwis5RIuEw='),
        ),
    ]
