# Generated by Django 3.0.6 on 2020-07-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secret',
            field=models.BinaryField(default=b'dnjsVbAOWiuNi5rBpYNmle5UKy6hgtNSBdfeHajYYiI='),
        ),
    ]
