# Generated by Django 3.0.6 on 2020-07-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secret',
            field=models.BinaryField(default=b'jAeeLCArJoCLjvgxi6iAQuvpW2jQIF8Jh3qHWUyGyRk='),
        ),
    ]
