# Generated by Django 3.0.6 on 2020-07-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secret',
            field=models.BinaryField(default=b'VxM6-GFsfst9PbS4TNYXfD1jshDm3NUCBPclDzt6WSE='),
        ),
    ]
