# Generated by Django 3.0.6 on 2020-06-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='couple_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
