# Generated by Django 3.0.6 on 2020-08-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secret',
            field=models.BinaryField(default=b'b7GRgZehJ7FuQBF6-ZOensvUJjalus9EJOnJ6sMlcFw='),
        ),
    ]
