# Generated by Django 3.0.6 on 2020-08-13 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_changed',
        ),
    ]
