# Generated by Django 3.0.6 on 2020-08-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20200803_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secret',
            field=models.BinaryField(default=b'moD6j3zLuJSu3IIkONyHas3t3K1qaonDojItgihmMNc='),
        ),
    ]
