# Generated by Django 3.0.6 on 2020-06-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_couple_couple_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('scores', models.CharField(default='[]', max_length=20)),
                ('personalities', models.TextField(default='[]')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='choice_data',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='user',
            name='deal_breaker',
            field=models.CharField(default='[]', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='jilted_matches',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='user',
            name='matches',
            field=models.CharField(default='[]', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='no_matches',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='user',
            name='notification',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='user',
            name='successful_matches',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_data',
            field=models.TextField(default='{}'),
        ),
    ]
