# Generated by Django 3.0.6 on 2020-09-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20200813_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='payed',
        ),
        migrations.AddField(
            model_name='user',
            name='package',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='successful_matches',
            field=models.TextField(default='[]'),
        ),
    ]
