# Generated by Django 3.0.6 on 2020-07-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20200705_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secret',
            field=models.BinaryField(default=b'RkBO9V7w3qj9s_T-V7ZR2x8oUpfQsc-lJ1rZKQUjPKs='),
        ),
    ]
