# Generated by Django 3.0.6 on 2020-07-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20200705_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secret',
            field=models.BinaryField(default=b'IsRrvLbngcGasDL2pvJ9IcvG5Xq_jopPZRX_R2d3wvo='),
        ),
    ]
