# Generated by Django 3.0.6 on 2020-09-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20200914_0441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='package',
        ),
        migrations.AddField(
            model_name='user',
            name='can_be_matched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='extra_support',
            field=models.BooleanField(default=False),
        ),
    ]
