# Generated by Django 3.0.6 on 2020-08-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20200731_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secret',
            field=models.BinaryField(default=b'a4VjqA8aeEn_uwPICA4cSpKgKOADykXJCU7QHlaS2S8='),
        ),
    ]
