# Generated by Django 3.0.6 on 2020-07-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_user_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='Offline', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='secret',
            field=models.BinaryField(default=b'SFJKwh5b-PVPEm-MLheOe-XVeKMGmsLsR8Qgj6QlK6w='),
        ),
    ]
