# Generated by Django 3.0.6 on 2020-08-05 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20200731_0647'),
        ('Account', '0004_auto_20200802_1334'),
    ]

    operations = [
    ]
