# Generated by Django 3.0.6 on 2020-07-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_auto_20200703_0503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalitytest',
            name='personalities',
        ),
        migrations.RemoveField(
            model_name='personalitytest',
            name='scores',
        ),
        migrations.AddField(
            model_name='personalitytest',
            name='agreeableness',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='personalitytest',
            name='conscientiousness',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='personalitytest',
            name='extraversion',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='personalitytest',
            name='neuroticism',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='personalitytest',
            name='openness',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='user',
            name='secret',
            field=models.BinaryField(default=b'4SPSNnMbPGnejKNddp4rzsejCJ23znvCnpizZqE7uQI='),
        ),
    ]
