# Generated by Django 3.0.6 on 2020-08-05 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_merge_20200805_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='secret',
        ),
    ]
