# Generated by Django 3.0.6 on 2020-07-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_auto_20200708_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='min_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='secret',
            field=models.BinaryField(default=b'Fo6XoXrHTFajgmqo3HXEbKzMKvfdR2qOEzRqc-pv9_Q='),
        ),
    ]
