# Generated by Django 3.0.6 on 2020-07-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_auto_20200716_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalitytest',
            old_name='neuroticism',
            new_name='neurotism',
        ),
        migrations.AlterField(
            model_name='user',
            name='secret',
            field=models.BinaryField(default=b'NlEaRRV7phvE_3qT_7pSe8eV9m53DpOKthGbsUzW5pY='),
        ),
    ]
