# Generated by Django 3.0.6 on 2020-07-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_auto_20200716_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secret',
            field=models.BinaryField(default=b'UvVrrVD29-wVrUktsH_nE6yvD9ZkHbkXJycNFO4qgN0='),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default='Offline', max_length=64),
        ),
    ]
