# Generated by Django 3.0.6 on 2020-07-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_auto_20200720_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secret',
            field=models.BinaryField(default=b'U3vYokpYt-ziUGMdQ-r8UZPa3YFC9KpbI3H1BT-hSTo='),
        ),
    ]
