# Generated by Django 3.0.6 on 2020-07-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_auto_20200725_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dating',
        ),
        migrations.RemoveField(
            model_name='user',
            name='min_score',
        ),
        migrations.AddField(
            model_name='user',
            name='couple_ids',
            field=models.CharField(default='[]', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='session',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='user',
            name='secret',
            field=models.BinaryField(default=b'vTQCWSv0hcC5SmxrB43cbhsi97gwKKKwf0jUvAKOaoI='),
        ),
    ]
