# Generated by Django 3.0.6 on 2020-09-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date_of_payment',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='payment',
            name='package',
            field=models.CharField(choices=[('BASIC', 'BASIC'), ('CLASSIC', 'CLASSIC'), ('PREMIUM', 'PREMIUM')], default='BASIC', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID'), ('FAILED', 'FAILED')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='tx_ref',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
