# Generated by Django 3.0.6 on 2020-09-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_auto_20200914_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='duration',
            field=models.CharField(blank=True, choices=[('QUARTERLY', 'QUARTERLY'), ('YEARLY', 'YEARLY')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='expiry_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_of_payment',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='package',
            field=models.CharField(choices=[('GUEST', 'GUEST'), ('REGULAR', 'REGULAR'), ('PREMIUM', 'PREMIUM')], default='BASIC', max_length=10),
        ),
    ]
