# Generated by Django 3.0.6 on 2020-09-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0003_auto_20200915_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='package',
            field=models.CharField(choices=[('REGULAR', 'REGULAR'), ('PREMIUM', 'PREMIUM')], default='BASIC', max_length=10),
        ),
    ]
