# Generated by Django 3.0.6 on 2020-07-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_chatthread_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatthread',
            name='first_deleted',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='chatthread',
            name='second_deleted',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='chatthread',
            name='secret',
            field=models.BinaryField(),
        ),
    ]
